# Generated by Django 4.1.7 on 2023-03-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnfew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCatery',
            new_name='BlogCategory',
        ),
    ]
